### ISSUE TITLE
Running Apexdoc w/o the -p scope tag set results in a runtime error

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/ApexDoc#28]
```
kbromer-ltm:Workspace kbromer$ java -jar apexdoc.jar 
-s '/Users/kbromer/Workspace/Cumulus/src/classes' 
-t '/Users/kbromer/Workspace/Cumulus_Apexdoc_Test' 
-g 'http://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/'
```
java.lang.ArrayIndexOutOfBoundsException: 3
	at org.salesforce.apexdoc.ApexDoc.RunApexDoc(ApexDoc.java:87)
	at org.salesforce.apexdoc.ApexDoc.main(ApexDoc.java:34)

Works fine if I include the optional param

**Comment by davidhabib** [comment]
fixed
