### ISSUE TITLE
Space in if statement causes error

### ISSUE THREAD

**Issue by fbairn** [SalesforceFoundation/ApexDoc#54]
I was getting an invalid argument error. I narrowed it down to a single if statement in one of my files.

An error shows up when this statement has spaces between c.commentPublic and !=
This works: if(c.commentPublic!=null){
This does not work: if(c.commentPublic !=null){

Version 1.1.5
Error log
	java.lang.NullPointerException
	at org.salesforce.apexdoc.ClassModel$1.compare(ClassModel.java:55)
	at org.salesforce.apexdoc.ClassModel$1.compare(ClassModel.java:1)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at org.salesforce.apexdoc.ClassModel.getMethodsSorted(ClassModel.java:48)
	at org.salesforce.apexdoc.FileManager.htmlForClassModel(FileManager.java:217)
	at org.salesforce.apexdoc.FileManager.makeFile(FileManager.java:143)
	at org.salesforce.apexdoc.FileManager.createDoc(FileManager.java:429)
	at org.salesforce.apexdoc.ApexDoc.RunApexDoc(ApexDoc.java:128)
	at org.salesforce.apexdoc.ApexDoc.main(ApexDoc.java:36)

**Comment by davidhabib** [comment]
the string "Public " is throwing off the pseudo-parsing.
